### ISSUE TITLE
TokenManager: wrong call of RequestBody.create

### ISSUE THREAD

**Issue by cjaentsch** [fiskaly/fiskaly-kassensichv-client-java#1]
The create method on RequestBody (okhttp3.9.0) is not correctly called in TokenManager.java:
`body = RequestBody.create(jsonBody, JSON);`

Correct would be this:
`body = RequestBody.create(JSON, jsonBody);`

**Comment by cjaentsch** [comment]
Still incorrect after latest update... Or are you using a different version of okhttp?

**Comment by auxdevelopment** [comment]
Since version 4.0.0 of OkHttp this signature has been [deprecated](https://github.com/square/okhttp/blob/parent-4.0.0/okhttp/src/main/java/okhttp3/RequestBody.kt#L167).

We are currently using version 4.0.1 of OkHttp as can be seen in the `build.gradle` file of the `client` project.
