### ISSUE TITLE
Update a transaction: querystring.last_revision should be integer

### ISSUE THREAD

**Issue by Greelings** [fiskaly/fiskaly-kassensichv-client-java#20]
I try to update a transaction, but I get this error:
`The provided last_revision number does not match the last revision number recorded for this transaction.`

So I specified the last_revision query parameter like this:
```
HttpUrl.Builder httpBuider = HttpUrl.parse(Fiskaly.API + "/tss/" + tssId + "/tx/" + transactionId).newBuilder();
httpBuider.addQueryParameter("last_revision", (String) transactionResponseMap.get("last_revision"));

request = new Request.Builder()
                    .url(httpBuider.build())
                    .put(RequestBody.create(Fiskaly.objectMapper.writeValueAsString(body), MediaType.parse("application/json")))
                    .build();
```

But it says that the last_revision parameter should be an Integer:
`querystring.last_revision should be integer`

So my question is: is it possible to pass an Integer via a query parameter with okhttp? I did not find nothing in the official documentation. Thank you.

**Comment by cjaentsch** [comment]
I just added "?last_revision=1" (or what ever revision you have) without using the httpBuilder. So maybe you try `httpBuider.build()+"?last_revision="+((String) transactionResponseMap.get("last_revision"))`

**Comment by Greelings** [comment]
Thank you for your response @cjaentsch Is it working for you?

I tried your solution:
request = new Request.Builder()
                    .url(Fiskaly.API + "/tss/" + tssId + "/tx/" + transactionId + "?last_revision=" + transactionResponseMap.get("last_revision"))
                    .put(RequestBody.create(Fiskaly.objectMapper.writeValueAsString(body), MediaType.parse("application/json")))
                    .build();

But I got the same message:
`querystring.last_revision should be integer`

**Comment by cjaentsch** [comment]
Yes, it works here. Can you println the value that you give into the url.

**Comment by cjaentsch** [comment]
If you do not have a last_revision because it's the creation (on PUT), then don't add the query parameter at all. "null" or empty does not seem to be a valid value.

**Comment by Greelings** [comment]
I found the problem
`transactionResponseMap.get("last_revision")` returns NULL

**Comment by Greelings** [comment]
last_revision do not exists... 
I need to use "revision" or "latest_revision"
Thank you very much for your help @cjaentsch
