### ISSUE TITLE
Size optimization

### ISSUE THREAD

**Issue by Greelings** [fiskaly/fiskaly-kassensichv-client-java#23]
Compiling my app, I noticed that the fiskaly-kassensichv library contains several "libgojni.so" files that have drastically increased the app size (5MB -> 25MB). Is there any way to optimize the size of the JAR file?

**Comment by auxdevelopment** [comment]
Currently there is no such mechanism. What you could do now as a quick fix would be removing the libraries you don't need from the JAR.

We will look into this as it is and will be a concern for multiple people and therefore needs a proper solution.

**Comment by Greelings** [comment]
Of course, no need to reduce the size at the moment. Only when it will be in production.
