### ISSUE TITLE
Empty certificate serial when I retrieve a transaction

### ISSUE THREAD

**Issue by Greelings** [fiskaly/fiskaly-kassensichv-client-java#35]
Here is the JSON object that is returned :
`{"number":225,"time_start":1574262044,"time_end":1574262045,"certificate_serial":"","type":"ORDER","state":"ACTIVE","client_id":"19314bd6-307c-378b-96d2-822574db1da1","data":{"aeao":{"receipt_type":"ORDER","line_items":[{"quantity":"1","text":"Coca","price_per_unit":"2.20"},{"quantity":"1","text":"Fanta","price_per_unit":"2.20"},{"quantity":"2","text":"Cesar salad","price_per_unit":"8.50"},{"quantity":"1","text":"Filet mignon","price_per_unit":"20.00"},{"quantity":"1","text":"Margherita pizza","price_per_unit":"15.00"}],"amounts_per_vat_rate":[{"vat_rate":"5.00","amount":"4.40"},{"vat_rate":"19.00","amount":"52.00"}],"amounts_per_payment_type":[{"payment_type":"CASH","amount":"56.40"}]}},"revision":1,"latest_revision":2,"log":{"operation":"StartTransaction","timestamp":1574262044},"signature":{"value":"AFqqBicgEupIQAeft5zwlgIt45mJjjkFMC507xGd63iuqIMB2C1oS7h/3mqF62KKZBJJoJWU8mLwwZQ0I7JHYw==","counter":441},"tss_id":"19314bd6-307c-378b-96d2-822574db1da1","metadata":{},"_type":"TRANSACTION","_id":"5d0d64dd-846f-34a4-b3d2-a04ccbf1014c"} `

As you can see the "certificate_serial" is empty.
However, this problem only occurs when I try to retrieve a transaction (https://kassensichv.io/api/docs/#operation/retrieveTransaction), NOT when I create one.

**Comment by prempador** [comment]
Thanks for the heads-up. 

We located the issue in our backend and applied a fix. I will inform you as soon as it is patched on the live system.

**Comment by Greelings** [comment]
Great job. Thank you.

**Comment by prempador** [comment]
@Greelings Just as a side-note. The same behavior appears to be in ListTransactions and ListAllTransactions. We are aware of this and fixed this in the same fix as mentioned above.

**Comment by Greelings** [comment]
Ok, perfect.

**Comment by prempador** [comment]
Bugfix is now on the live system. Thanks again for the report.
