### ISSUE TITLE
SmaLoader: On MacOS wrong libPath

### ISSUE THREAD

**Issue by cjaentsch** [fiskaly/fiskaly-kassensichv-client-java#7]
https://github.com/fiskaly/fiskaly-kassensichv-client-java/blob/9553b8250a5f511a2a409c7f3148d804a850cd30/sma-general/src/main/java/com/fiskaly/kassensichv/sma/SmaLoader.java#L70

On our MacBooks System.getProperty("os.name") returns "mac os x" not "darwin". So the lib path is not constructed correctly.

**Comment by auxdevelopment** [comment]
Should now be fixed by [this](https://github.com/fiskaly/fiskaly-kassensichv-client-java/pull/11)
