### ISSUE TITLE
SmaLoader: set different path for library

### ISSUE THREAD

**Issue by cjaentsch** [fiskaly/fiskaly-kassensichv-client-java#8]
As we would like to ship one JAVA-application in the end, but including all SMA-libs is an overload, it would be nice to have the possibility to disable the unpackLibraryIntoTempDirectory method as we already copied the SMA-lib into the JAVA tmp dir.

Something like:

public class SmaLoader {
    public static Boolean skipUnpackLibrary = false;
    public static SmaLibrary load() throws IOException {
        if (!SmaLoader.skipUnpackLibrary) {
               unpackLibraryIntoTempDirectory();
        }
        ....
    }
}

**Comment by pgaubatz** [comment]
Hi! Don't you think that parametrizing the build process in such a way, that one can choose which libraries get bundled, would be more suitable? The problem with your approach is that you'd "destroy" our SMA update mechanism.

**Comment by cjaentsch** [comment]
We ship one jar which should run on "every" hardware, but we don't want to have all SMAs bundled as it would be too large. So for us it would be best to lazy load the SMAs from our servers (we already implemented this now and it works fine). I wasn't aware of an SMA update mechanism in your client yet. So basically you have kind of the same mechanism with update of the SMA lib from a remote server? Then why not extend this not only to update the SMA lib but also to download the initial version of the SMA lib?

**Comment by cjaentsch** [comment]
So to make it clear as we have built it now: We don't bundle the SMA libs into the jar but have them down loadable on our servers. The jar detects on starting if the corresponding SMA lib for the current OS and hardware is already downloaded. If not, then it downloads it (for if started with a "force download" to force an update). We would always have the current versions of the SMAs on our servers so our jars would update them if necessary.

**Comment by pgaubatz** [comment]
Hi @cjaentsch! This repository has been deprecated. The new SDK can be found at https://github.com/fiskaly/fiskaly-sdk-java
