### ISSUE TITLE
404 when trying to finish transactions through SMA

### ISSUE THREAD

**Issue by cjaentsch** [fiskaly/fiskaly-kassensichv-client-java#9]
Start transaction works:
`PUT https://kassensichv.io/api/v0/tss/0e709b9a-9e09-4d48-9680-c1810a1e45c3/tx/e09bf758-d9a2-449e-bb34-af6815d76389`

Finish transaction does not work:
`PUT https://kassensichv.io/api/v0/tss/0e709b9a-9e09-4d48-9680-c1810a1e45c3/tx/e09bf758-d9a2-449e-bb34-af6815d76389?last_revision=1`

404 E_NOT_FOUND "Path does not exist"

When not requesting through the SMA but to the cloud directly, it works with both requests.

**Comment by auxdevelopment** [comment]
Should be fixed by [this](https://github.com/fiskaly/fiskaly-kassensichv-client-java/pull/12)
